# Generated by Django 3.1.3 on 2020-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201206_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
