# Generated by Django 3.1.3 on 2020-12-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201206_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='birth_date',
        ),
    ]
