# Generated by Django 3.1.3 on 2020-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofilemodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
